### ISSUE TITLE
Add symfony components in dependencies

### ISSUE THREAD

**Issue by mmoreram** [egulias/ListenersDebugCommandBundle#25]
- Would be a good practice only require desired Symfony dependencies.
- Also whould be a good practice require the best Symfony Component version: Actually is set to `>=2.3` but maybe the best option i `~2.3`, to avoid the `3.0` version

**Comment by egulias** [comment]
Hi @mmoreram 
The desired Symfony dependencies are in the lib (https://github.com/egulias/ListenersDebug), this being the integration into the Symfony framework. That's why is required fully, you suggest to require only the framework bundle and the ones required by the lib?

You are totally right regarding the version, I'll change it unless you want to provide a PR.

**Comment by mmoreram** [comment]
@egulias I had a text with my explanation, but a pair of PR are faster XD
